CREATE TABLE ref_alumni_info (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    real_name VARCHAR(64) NOT NULL,
    gender TINYINT NULL,
    graduation_year INT NULL,
    college VARCHAR(100) NULL,
    major VARCHAR(100) NULL,
    company_id BIGINT NULL,
    company_name VARCHAR(128) NULL,
    industry VARCHAR(64) NULL,
    position_name VARCHAR(100) NULL,
    city VARCHAR(64) NULL,
    referral_permission TINYINT DEFAULT 1,
    intro VARCHAR(500) NULL,
    verify_status TINYINT DEFAULT 0,
    creator VARCHAR(64) NULL,
    create_time DATETIME NULL,
    updater VARCHAR(64) NULL,
    update_time DATETIME NULL,
    deleted BIT DEFAULT b'0'
);

CREATE TABLE ref_student_info (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    real_name VARCHAR(64) NOT NULL,
    gender TINYINT NULL,
    student_no VARCHAR(64) NULL,
    college VARCHAR(100) NULL,
    major VARCHAR(100) NULL,
    grade VARCHAR(32) NULL,
    education VARCHAR(32) NULL,
    expected_industry VARCHAR(64) NULL,
    expected_job VARCHAR(100) NULL,
    expected_city VARCHAR(64) NULL,
    skill_tags VARCHAR(255) NULL,
    resume_url VARCHAR(255) NULL,
    intro VARCHAR(500) NULL,
    creator VARCHAR(64) NULL,
    create_time DATETIME NULL,
    updater VARCHAR(64) NULL,
    update_time DATETIME NULL,
    deleted BIT DEFAULT b'0'
);

CREATE TABLE ref_company_info (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_name VARCHAR(128) NOT NULL,
    industry VARCHAR(64) NULL,
    company_size VARCHAR(64) NULL,
    city VARCHAR(64) NULL,
    address VARCHAR(255) NULL,
    company_desc VARCHAR(500) NULL,
    official_website VARCHAR(255) NULL,
    status TINYINT DEFAULT 1,
    creator VARCHAR(64) NULL,
    create_time DATETIME NULL,
    updater VARCHAR(64) NULL,
    update_time DATETIME NULL,
    deleted BIT DEFAULT b'0'
);

CREATE TABLE ref_job_info (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    alumni_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    job_title VARCHAR(100) NOT NULL,
    job_type VARCHAR(64) NULL,
    industry VARCHAR(64) NULL,
    city VARCHAR(64) NULL,
    salary_range VARCHAR(64) NULL,
    education_requirement VARCHAR(64) NULL,
    experience_requirement VARCHAR(64) NULL,
    skill_requirement VARCHAR(255) NULL,
    job_desc VARCHAR(1000) NULL,
    contact_type VARCHAR(32) NULL,
    referral_quota INT DEFAULT 1,
    status TINYINT DEFAULT 0,
    audit_status TINYINT DEFAULT 0,
    publish_time DATETIME NULL,
    expire_time DATETIME NULL,
    creator VARCHAR(64) NULL,
    create_time DATETIME NULL,
    updater VARCHAR(64) NULL,
    update_time DATETIME NULL,
    deleted BIT DEFAULT b'0'
);

CREATE TABLE ref_referral_application (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    job_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    alumni_id BIGINT NOT NULL,
    resume_url VARCHAR(255) NULL,
    self_introduction VARCHAR(500) NULL,
    match_score DECIMAL(5,2) NULL,
    apply_status TINYINT DEFAULT 0,
    process_remark VARCHAR(500) NULL,
    apply_time DATETIME NULL,
    process_time DATETIME NULL,
    creator VARCHAR(64) NULL,
    create_time DATETIME NULL,
    updater VARCHAR(64) NULL,
    update_time DATETIME NULL,
    deleted BIT DEFAULT b'0'
);

CREATE TABLE ref_consult_message (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    job_id BIGINT NULL,
    sender_user_id BIGINT NOT NULL,
    receiver_user_id BIGINT NOT NULL,
    sender_role TINYINT NOT NULL,
    receiver_role TINYINT NOT NULL,
    content VARCHAR(1000) NOT NULL,
    read_status TINYINT DEFAULT 0,
    send_time DATETIME NULL,
    creator VARCHAR(64) NULL,
    create_time DATETIME NULL,
    updater VARCHAR(64) NULL,
    update_time DATETIME NULL,
    deleted BIT DEFAULT b'0'
);
